Remove Spring
During the upgrade to Rails 7 Spring is causing the following error:

undefined method `mechanism=' for ActiveSupport::Dependencies:Module

Rails 7 is moving away from Spring and it is no longer the default.